In [1]:
import numpy as np

In [2]:
arr1 = np.zeros(10, dtype = int)

In [3]:
arr1.size

10

In [4]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000024565A387F0>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [5]:
arr2 = np.zeros(10, dtype = int)
arr2[4] = 1
arr2

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [6]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [7]:
# import shuffle from random
np.random.seed(140)
arr3 = np.random.randint(1,20, (3,3))
print(f'{arr3}  \n\n')
np.random.shuffle(arr3)
print(arr3)
arr3[::-1]

[[ 9  7 14]
 [17  1  4]
 [ 8 19  5]]  


[[ 8 19  5]
 [ 9  7 14]
 [17  1  4]]


array([[17,  1,  4],
       [ 9,  7, 14],
       [ 8, 19,  5]])

In [8]:
np.random.seed(1234)
arr4 = np.random.randint(0,8, (3,3))
arr4

array([[7, 3, 6],
       [5, 4, 4],
       [0, 1, 7]])

In [9]:
arr5 = np.arange(9)
arr5.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
li = [1,2,0,0,4,0]
li2 =[i for i,v in enumerate(li) if v!= 0 ] 
li2
np.nonzero(li)

(array([0, 1, 4], dtype=int64),)

In [11]:
np.random.seed(1234)
arr5 = np.random.rand(3,3)
arr5

array([[0.19151945, 0.62210877, 0.43772774],
       [0.78535858, 0.77997581, 0.27259261],
       [0.27646426, 0.80187218, 0.95813935]])

In [12]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
arr6 = np.random.rand(3,3,3)
arr6

array([[[0.87593263, 0.35781727, 0.50099513],
        [0.68346294, 0.71270203, 0.37025075],
        [0.56119619, 0.50308317, 0.01376845]],

       [[0.77282662, 0.88264119, 0.36488598],
        [0.61539618, 0.07538124, 0.36882401],
        [0.9331401 , 0.65137814, 0.39720258]],

       [[0.78873014, 0.31683612, 0.56809865],
        [0.86912739, 0.43617342, 0.80214764],
        [0.14376682, 0.70426097, 0.70458131]]])

In [14]:
arr7 = np.random.randint(0,30,(10,10))
arr7.argmin() , arr7.argmax()

(54, 3)

In [15]:
arr8 = np.arange(30)
np.mean(arr8)

14.5

In [16]:
arr9 = np.zeros((3,3) ,dtype = int)
arr9[0] = 1
arr9[0:3,0] = 1
arr9

array([[1, 1, 1],
       [1, 0, 0],
       [1, 0, 0]])

In [17]:
arr10= np.zeros((3,3) ,dtype = int)
arr10[1:-1,1:-1]

array([[0]])

In [18]:
arr11 = np.ones((5,5), dtype = int)
arr11
# np.diag(arr11) = ([1,2,3,4,5])

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [20]:
np.eye(5, k=-2)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [21]:
np.diag(np.arange(1,5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [22]:
arr12 = np.random.randint(1,50, (8,8))
arr12

array([[ 9,  3, 17, 44,  3, 16,  4, 47],
       [35, 37, 25, 34, 43,  3, 24, 46],
       [21, 36, 19, 13,  6, 18, 17,  9],
       [46, 12, 16, 21, 17,  1, 33, 20],
       [20, 28, 24, 42, 36, 37, 21, 29],
       [ 2, 12, 18, 31, 39, 35, 26, 40],
       [25, 13, 13, 33,  9, 48, 24, 26],
       [46, 22, 23, 46, 20, 42, 48, 37]])

In [23]:
arr12[0:, ::2] 
arr12

array([[ 9,  3, 17, 44,  3, 16,  4, 47],
       [35, 37, 25, 34, 43,  3, 24, 46],
       [21, 36, 19, 13,  6, 18, 17,  9],
       [46, 12, 16, 21, 17,  1, 33, 20],
       [20, 28, 24, 42, 36, 37, 21, 29],
       [ 2, 12, 18, 31, 39, 35, 26, 40],
       [25, 13, 13, 33,  9, 48, 24, 26],
       [46, 22, 23, 46, 20, 42, 48, 37]])

In [24]:
arr12[1::2,::2]=0
arr12

array([[ 9,  3, 17, 44,  3, 16,  4, 47],
       [ 0, 37,  0, 34,  0,  3,  0, 46],
       [21, 36, 19, 13,  6, 18, 17,  9],
       [ 0, 12,  0, 21,  0,  1,  0, 20],
       [20, 28, 24, 42, 36, 37, 21, 29],
       [ 0, 12,  0, 31,  0, 35,  0, 40],
       [25, 13, 13, 33,  9, 48, 24, 26],
       [ 0, 22,  0, 46,  0, 42,  0, 37]])

In [25]:
arr12[::2,1::2] = 0
arr12

array([[ 9,  0, 17,  0,  3,  0,  4,  0],
       [ 0, 37,  0, 34,  0,  3,  0, 46],
       [21,  0, 19,  0,  6,  0, 17,  0],
       [ 0, 12,  0, 21,  0,  1,  0, 20],
       [20,  0, 24,  0, 36,  0, 21,  0],
       [ 0, 12,  0, 31,  0, 35,  0, 40],
       [25,  0, 13,  0,  9,  0, 24,  0],
       [ 0, 22,  0, 46,  0, 42,  0, 37]])

In [26]:
arr12[1::2,1::2] =1
arr12

array([[ 9,  0, 17,  0,  3,  0,  4,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  1],
       [21,  0, 19,  0,  6,  0, 17,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  1],
       [20,  0, 24,  0, 36,  0, 21,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  1],
       [25,  0, 13,  0,  9,  0, 24,  0],
       [ 0,  1,  0,  1,  0,  1,  0,  1]])

In [27]:
arr13 = np.zeros((8,8))
arr13

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
arr13[0::2,1::2] = 1
arr13

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
arr13[1::2,::2] = 1
arr13

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [30]:
arr14 = np.random.randint(0,50, (6,7,8))


In [31]:
np.unravel_index(100, (6,7,8))### query

(1, 5, 4)

In [32]:
np.set_printoptions(linewidth=10000)

In [33]:
arr21 = np.ones((4,4) , dtype = 'int') 
arr21[0::2,::2] = 0
arr21[1::2,1::2] = 0
arr21

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 0, 1],
       [1, 0, 1, 0]])

In [34]:
arr21_ = np.tile(arr21,(2,2))
arr21_

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [35]:
np.random.seed(1234)
arr22 = np.random.random((5,5))
arr22

array([[0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581],
       [0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263],
       [0.35781727, 0.50099513, 0.68346294, 0.71270203, 0.37025075],
       [0.56119619, 0.50308317, 0.01376845, 0.77282662, 0.88264119],
       [0.36488598, 0.61539618, 0.07538124, 0.36882401, 0.9331401 ]])

In [36]:
arr22_ = (arr22-np.mean(arr22))/np.std(arr22)
arr22_

array([[-1.34928699,  0.27720685, -0.41926795,  0.89386129,  0.87352857],
       [-1.04304394, -1.0284193 ,  0.95623919,  1.54651765,  1.23599271],
       [-0.72111911, -0.18028382,  0.50896404,  0.61941082, -0.67415328],
       [ 0.04711767, -0.17239653, -2.02071774,  0.84652347,  1.26133339],
       [-0.69441799,  0.25185093, -1.78798362, -0.67954263,  1.45208631]])

In [37]:
arr22max, arr22min = arr22.max(), arr22.min()

arr22_1 = (arr22-arr22min)/(arr22max-arr22min)
arr22_1

array([[0.1882216 , 0.64417521, 0.44893303, 0.81704141, 0.81134156],
       [0.27407045, 0.27817016, 0.83452775, 1.        , 0.91295081],
       [0.36431535, 0.51592724, 0.7091435 , 0.74010495, 0.37748125],
       [0.57967451, 0.51813828, 0.        , 0.80377124, 0.92005454],
       [0.37180046, 0.6370672 , 0.06524215, 0.37597045, 0.97352814]])

In [38]:
np.random.seed(1324)
arr24 = np.dot(np.random.random((5,3)),np.random.random((3,2)))
arr24

array([[0.82069713, 0.81908455],
       [0.95299787, 0.90574182],
       [0.95949821, 0.58086777],
       [0.12479078, 0.29073073],
       [0.19692357, 0.55722968]])

In [39]:
arr24_ = np.dot(np.ones((5,3), dtype = 'int'), np.ones((3,2), dtype = 'int'))
arr24_

array([[3, 3],
       [3, 3],
       [3, 3],
       [3, 3],
       [3, 3]])

In [40]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [41]:
arr25 = np.arange(11)
arr25[(arr25 > 3) & (arr25 <= 8)] *= -1
print(arr25)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [42]:
arr25 = [-i for i in arr25 if i > 3 and i <= 8]
arr25

[]

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [122]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.147e+09]


In [44]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


<ipython-input-44-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-44-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


In [45]:
np.set_printoptions(precision = 3 , linewidth= 100000)

In [46]:
np.random.seed(123)
arr29 = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(arr29)), arr29))
arr29

[ 4. -5. -6.  2.  5. -2. 10.  4. -1. -3.]


array([ 3.929, -4.277, -5.463,  1.026,  4.389, -1.538,  9.615,  3.697, -0.381, -2.158])

In [47]:
np.ceil(np.abs(arr29))

array([ 4.,  5.,  6.,  2.,  5.,  2., 10.,  4.,  1.,  3.])

In [48]:
arr30 = np.random.uniform(0,10,6)
arr30_ = np.random.uniform(0,10,6)
np.intersect1d(arr30, arr30_)

array([], dtype=float64)

In [49]:
# defaults = np.seterr(all = 'ignore')
arr31 = np.ones(1) / 0
arr31

<ipython-input-49-ed648c6c97e7>:2: RuntimeWarning: divide by zero encountered in true_divide
  arr31 = np.ones(1) / 0


array([inf])

In [50]:
np.sqrt(-1) ==   np.emath.sqrt(-1)


<ipython-input-50-fb23fa3cbb44>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) ==   np.emath.sqrt(-1)


False

In [51]:
a35 = np.ones((3,3))
a35a = np.full((3,3), fill_value = 2)
a = np.add(a35, a35a)
b = np.divide(-a35, 2)
a*b

array([[-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5],
       [-1.5, -1.5, -1.5]])

In [63]:
print(arr30)
print(np.floor(arr30))
p = (np.trunc(arr30))
print(arr30.astype(int))

[3.432 7.29  4.386 0.597 3.98  7.38 ]
[3. 7. 4. 0. 3. 7.]
[3 7 4 0 3 7]


In [83]:
a37 = np.zeros((5,5), dtype = 'int') 
a37 += np.arange(5, dtype = 'int')
# np.hstack(a37)
a37

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [85]:
a37_ = np.tile(np.arange(0, 5), (5,1))
a37_

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [93]:
a39 = np.linspace(0,1,10,endpoint=True)[1:-1]
print(a39)
# np.size(Z)

[0.111 0.222 0.333 0.444 0.556 0.667 0.778 0.889]


In [55]:
arr39 = np.random.ranf((1,9))
arr39

array([[0.724, 0.611, 0.722, 0.323, 0.362, 0.228, 0.294, 0.631, 0.092]])

In [102]:
a40 = np.random.random(15)
np.sort(a40)

array([0.044, 0.151, 0.305, 0.356, 0.357, 0.389, 0.398, 0.554, 0.593, 0.692, 0.705, 0.763, 0.842, 0.925, 0.995])

In [109]:
a41 = np.random.randint(5,60, (3,3))
print(a41)
np.add.reduce(a41)

[[29 51 28]
 [10 38 55]
 [42  7 23]]


array([ 81,  96, 106])

In [120]:
np.random.seed(789)
a42 = np.arange(5,30).reshape((5,5))
a42_ = np.arange(5,30).reshape((5,5))
print(a42, '\n\n', a42_)
(a42 == a42_)

[[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]] 

 [[ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [16]:
arr45 = np.random.randint(2,50,  size = 10)
arr45

array([ 3, 48, 25, 23, 47,  8, 49,  4, 20, 15])

In [24]:
np.where(arr45 == np.max(arr45))

SyntaxError: cannot assign to function call (<ipython-input-24-291900fa9b09>, line 1)

In [8]:
arr = np.array([10, 15, 20, 25, 30, 35, 40])


In [15]:
arr[::2]


array([10, 20, 30, 40])

In [3]:
arr52 = np.random.random((10,2))
arr52

array([[0.44634169, 0.01183657],
       [0.87832984, 0.89311514],
       [0.94631234, 0.6853462 ],
       [0.71982065, 0.46381939],
       [0.87197818, 0.50630518],
       [0.47288589, 0.11510363],
       [0.30730797, 0.7206878 ],
       [0.55818752, 0.45575405],
       [0.46299029, 0.84148542],
       [0.73153472, 0.61794164]])

In [20]:
m = np.max(arr45) 
m = 0

In [21]:
arr45

array([ 3, 48, 25, 23, 47,  8, 49,  4, 20, 15])